### ISSUE TITLE
Support Higher Order Components?  

### ISSUE THREAD

**Issue by mmacaula** [jozsi/react-cosmos-wrapper-proxy#1]
Would be nice to have another export (or option) that would work with HOCs.  

My use case is ReduxForm.  See  https://github.com/react-cosmos/react-cosmos/issues/576#issuecomment-361820258  It seems like I'm asking for trouble to wrap my component in the HOC inside the fixture.  

Would be interested in helping if you like.  Thoughts?

**Comment by jozsi** [comment]
Hey @mmacaula !

It's [planned](https://github.com/react-cosmos/react-cosmos/issues/568) - now that I see there's request for it, I'll re-prioritize my tasks and try to do it this week :)

**Comment by jozsi** [comment]
[It landed](https://github.com/jozsi/react-cosmos-wrapper-proxy#hoc) in `v1.2.0` 🎉
