### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by jnv** [jozsi/react-cosmos-wrapper-proxy#6]
Hi, I have noticed you have added `defaultEnabled` feature in #4 which would be super nice to have. Would you please create and publish a new release to npm? Thank you!

**Comment by jozsi** [comment]
Sure, @jnv - I'll publish a new version later today. Thanks for the heads up!

**Comment by jozsi** [comment]
`v1.5.0` has been released and published to npm. A big thanks again to @tgrowden!

**Comment by jnv** [comment]
Thank you for such a quick response!

**Comment by jozsi** [comment]
My pleasure! FYI, meanwhile I realized an edge case and handled it under [v1.6.0](https://github.com/jozsi/react-cosmos-wrapper-proxy/releases/tag/v1.6.0).
